#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Min Spanning Tree by class w Laplacian

Created on Wed Jul 17 13:12:58 2019

@author: deborah
"""


import numpy as np
import pandas as pd
from copy import copy
import Data_Mod_Functions as dm
import Calculate_Distance as cd
import Accuracy_Predictions_Functions as ap
import Graph_Building_Functions as gb

def main():
    # Load dataset from website to array and normalize data
    url = "https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data"
    column_names = ['sepal-length', 'sepal-width', 'petal-length', 'petal-width', 'class']
    label_column = -1

    # read in data and store in an array
    data_frame = pd.read_csv(url, names = column_names)
    array = data_frame.values
    norm_data = dm.normalize(array)

    # extract labels from data
    labels = dm.extract_labels (copy(norm_data), label_column)

    # calculate weights for distance metric using one-way ANOVA for each attribute
    weights = cd.calculate_attribute_strength(copy(norm_data), labels, True)
    print(weights)

    # calculate distance between all points pair-wise
    mapped_distances = cd.calculate_wminkowski_pdist (copy(norm_data), label_column, weights)

    # split data and get predictions
    num_groups = 5
    num_iterations = 8

    # create data_class matrix
    data_class = dm.extract_classifications(copy(norm_data), label_column)

    iteration_accuracy = []
    overall_accuracy = []

    # use each group as test group once each; use all other groups for training
    for l in range(num_iterations):

        # Split data into groups for cross validation
        split_indices = dm.split_groups (copy(norm_data), num_groups, label_column)
        iteration_accuracy = []

        for j in range(num_groups):

            # Split data into training/testing groups
            test_indices = copy(split_indices[j,:])
            train_indices = np.array(sorted(copy(np.delete(copy(split_indices), j, 0).flatten())))

            # compute the laplacian
            laplacian, degrees = gb.mst_by_class(copy(mapped_distances), norm_data.shape[0], train_indices, test_indices, labels, label_column, norm_data)

            # use nearest neighbors to predict tags for test group
            predictions = ap.get_predictions_reduced_Lap (test_indices, train_indices, copy(data_class), laplacian)

            # evaluate accuracy of model
            prediction_accuracy = ap.calculate_accuracy_num (test_indices, predictions, copy(norm_data), labels)
            iteration_accuracy = np.append(iteration_accuracy, prediction_accuracy)
        # calculate and print the average accuracy of the algorithm

        print("Average Accuracy of Test (Cross Validated) #{0}: {1:.2f}% \n".format(l+1, np.average(iteration_accuracy)))
        overall_accuracy = np.append(overall_accuracy, np.average(iteration_accuracy))

    print()
    print("Average Accuracy of Algorithm: {:.2f}%".format(np.average(overall_accuracy)))


if __name__== "__main__":
    main()
